/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMaterialSymbolsAccountCircle: typeof import('~icons/material-symbols/account-circle.jsx').default
  const IconMaterialSymbolsAccountCircleOutline: typeof import('~icons/material-symbols/account-circle-outline.jsx').default
  const IconMaterialSymbolsArrowBack: typeof import('~icons/material-symbols/arrow-back.jsx').default
  const IconMaterialSymbolsHome: typeof import('~icons/material-symbols/home.jsx').default
  const IconMaterialSymbolsHomeOutline: typeof import('~icons/material-symbols/home-outline.jsx').default
  const IconMaterialSymbolsNotifications: typeof import('~icons/material-symbols/notifications.jsx').default
  const IconMaterialSymbolsNotificationsOutline: typeof import('~icons/material-symbols/notifications-outline.jsx').default
  const IconMaterialSymbolsSearch: typeof import('~icons/material-symbols/search.jsx').default
  const IconMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings.jsx').default
  const IconMaterialSymbolsSettingsOutline: typeof import('~icons/material-symbols/settings-outline.jsx').default
  const IconMaterialSymbolsTag: typeof import('~icons/material-symbols/tag.jsx').default
  const IconMdiAccountCircle: typeof import('~icons/mdi/account-circle.jsx').default
  const IconMdiAccountPlus: typeof import('~icons/mdi/account-plus.jsx').default
  const IconMdiCheck: typeof import('~icons/mdi/check.jsx').default
  const IconMdiClock: typeof import('~icons/mdi/clock.jsx').default
  const IconMdiClockOutline: typeof import('~icons/mdi/clock-outline.jsx').default
  const IconMdiClose: typeof import('~icons/mdi/close.jsx').default
  const IconMdiGlobe: typeof import('~icons/mdi/globe.jsx').default
  const IconMdiLock: typeof import('~icons/mdi/lock.jsx').default
  const IconMdiMessageReplyTextOutline: typeof import('~icons/mdi/message-reply-text-outline.jsx').default
  const IconMdiPencilOutline: typeof import('~icons/mdi/pencil-outline.jsx').default
  const IconMdiShield: typeof import('~icons/mdi/shield.jsx').default
  const IconMdiShieldOutline: typeof import('~icons/mdi/shield-outline.jsx').default
}
